<div class="col-11 col-md-9" id="form-container">
    <div class="align-items-center">
        <div class="d-flex justify-content-between">
            <h2>Todos os treinamentos</h2>
        </div>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Treinamento</th>
                    <th id="th-actions">Ações</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($trainings as $training) : ?>
                    <tr>
                        <th><?= $training->getId() ?></th>
                        <td>
                            <p><?= $training->getName(); ?></p>
                        </td>
                        <td class="text-end d-flex justify-content-end gap-2">
                            <a href="/trainings/<?= $training->getId() ?>/edit" class="btn btn-outline-primary mt-0">
                                Editar
                            </a>
                            <form action="/trainings" method="POST" class="d-inline-block">
                                <input type='hidden' name="_method" value='DELETE'>
                                <input type="hidden" name="training[id]" value="<?= $training->getId() ?>">
                                <button type="submit" class="btn btn-danger">
                                    <i class="bi bi-trash"></i>
                                </button>
                            </form>
                        </td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>
