services:
  web:
    image: nginx:latest
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./server/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public/assets:/var/www/public/assets:rw
    ports:
      - 80:80
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./public/assets:/var/www/public/assets:rw
    networks:
      - app-network
  db:
    image: mysql:8.1.0
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: "$DB_DATABASE"
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_USER: "$DB_USERNAME"
      MYSQL_PASSWORD: "$DB_PASSWORD"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
