<div class="container col-11 col-md-9" id="form-container">
    <div class="row align-items-center gx-5">
        <div class="col-md-6 order-md-2">
            <h2>Faça o login para continuar</h2>
            <form action="/login" method="POST">
                <div class="form-floating mb-3">
                    <input type="email" class="form-control" id="user_email" name="user[email]" placeholder="Digite o seu email" />
                    <label for="user_email" class="form-label">Digite o seu
                        e-mail</label>
                </div>
                <div class="form-floating mb-3">
                    <input type="password" class="form-control" id="user_password" name="user[password]" placeholder="Digite a sua senha" />
                    <label for="user_password" class="form-label">Digite a sua
                        senha</label>
                </div>
                <input class="btn btn-primary" type="submit" value="Entrar" />
            </form>
        </div>

        <div class="col-md-6 order-md-1">
            <div class="col-12">
                <img src="/assets/images/sign_in.svg" alt="Entrar no sistema" class="img-fluid" />
            </div>
        </div>
    </div>
</div>
