<!-- <form action="/login" method="POST">
  <div class="form-group">
    <label for="user_email">Email</label>
    <input id="user_email" type="email" name="user[email]">
  </div>
  <div class="form-group">
    <label for="user_password">Senha</label>
    <input id="user_password" type="password" name="user[password]">
  </div>
  <input type="submit" value="Entrar">
</form> -->

<main>
  <div class="container col-11 col-md-9" id="form-container">
    <div class="row align-items-center gx-5">
      <div class="col-md-6 order-md-2">
        <h2>Faça o login para continuar</h2>
        <form action="/login" method="POST">
          <div class="form-floating mb-3">
            <input type="email" class="form-control" id="user_email" name="user[email]" placeholder="Digite o seu email" />
            <label for="user_email" class="form-label">Digite o seu
              e-mail</label>
          </div>
          <div class="form-floating mb-3">
            <input type="password" class="form-control" id="user_password" name="user[password]" placeholder="Digite a sua senha" />
            <label for="user_password" class="form-label">Digite a sua
              senha</label>
          </div>
          <input class="btn btn-primary" type="submit" value="Entrar" />
        </form>
      </div>

      <div class="col-md-6 order-md-1">
        <div class="col-12">
          <img src="/assets/images/sign_in.png" alt="Entrar no sistema" class="img-fluid" />
        </div>
        <div class="col-12" id="link-container">
          <a href="register.html">Ainda não tenho cadastro</a>
        </div>
      </div>
    </div>
  </div>
</main>