<div class="container col-11 col-md-9" id="form-container">
    <div class="row gx-5">
        <div class="col-md-6">
            <h2>Cadastrar Colaborador</h2>
            <?php $simpleForm->for($user, '/register', 'POST', function ($form) use ($user) { ?>
                <?= $form->inputFor('name', 'Nome') ?>
                <?= $form->inputFor('email', 'Email', 'email') ?>
                <?= $form->inputFor('password', 'Senha', 'password') ?>
                <?= $form->inputFor('password_confirmation', 'Confirmação de Senha', 'password') ?>
                <?= $form->checkboxFor('is_admin', 'É um usuário administrador?') ?>

                <?= $form->submit('Cadastrar') ?>
            <?php }) ?>
        </div>
        <div class="col-md-6">
            <div class="row align-items-center">
                <div class="col-12">
                    <img src="assets/images/new_user.svg" alt="Tela de Cadastro de colaborador" class="img-fluid" />
                </div>
            </div>
        </div>
    </div>
</div>
