<?php $simpleForm->for($user, '/sign-up', 'POST', function ($form) use ($user) { ?>
<?= $form->inputFor('name', 'Nome') ?>
<?= $form->inputFor('email', 'Email', 'email') ?>
<?= $form->inputFor('password', 'Senha', 'password') ?>
<?= $form->inputFor('password_confirmation', 'Confirmação de Senha', 'password') ?>

<?= $form->submit('Registrar-se') ?>
<?php }) ?>

<main>
  <div class="container col-11 col-md-9" id="form-container">
    <div class="row gx-5">
      <div class="col-md-6">
        <h2>Realize seu cadastro</h2>
        <form>
          <div class="form-floating mb-3">
            <input type="text" class="form-control" id="name" name="name"
              placeholder="Digite o seu nome" />
            <label for="name" class="form-label">Digite o seu nome</label>
          </div>
          <div class="form-floating mb-3">
            <input type="text" class="form-control" id="lastname"
              name="lastname" placeholder="Digite o seu sobrenome" />
            <label for="lastname" class="form-label">Digite o seu
              sobrenome</label>
          </div>
          <div class="form-floating mb-3">
            <input type="email" class="form-control" id="email" name="email"
              placeholder="Digite o seu e-mail" />
            <label for="email" class="form-label">Digite o seu e-mail</label>
          </div>
          <div class="form-floating mb-3">
            <input type="password" class="form-control" id="password"
              name="password" placeholder="Digite sua senha" />
            <label for="password" class="form-label">Digite sua senha</label>
          </div>
          <div class="form-floating mb-3">
            <input type="password" class="form-control" id="confirmpassword"
              name="confirmpassword" placeholder="Confirme sua senha" />
            <label for="confirmpassword" class="form-label">Confirme sua
              senha</label>
          </div>
          <div class="mb-3">
            <div class="form-check mb-2">
              <input type="checkbox" class="form-check-input" value=""
                id="agree-form" name="agree-form" />
              <label for="agree-form" class="form-check-label">Você aceita os <a
                  href="#">termos de serviço</a>?</label>
            </div>
            <div class="form-check mb-2">
              <input type="checkbox" class="form-check-input" checked
                id="newslatter" name="newslatter" />
              <label for="newslatter" class="form-check-label">Deseja receber
                nossas Newslatter?</label>
            </div>
            <input type="submit" class="btn btn-primary" value="Cadastrar" />
          </div>
        </form>
      </div>
      <div class="col-md-6">
        <div class="row align-items-center">
          <div class="col-12">
            <img src="assets/images/hello.svg" alt="Tela de Registro"
       
       class="img-fluid" />
          </div>
          <div class="col-12" id="link-container">
            <a href="/login">Eu já tenho uma conta</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>