<h1>Todos os usuários</h1>

<table>
    <thead>
        <th>ID</th>
        <th>Nome</th>
    </thead>
    <tbody>
        <?php foreach ($paginator->registers() as $user) : ?>
            <tr>
                <td><?= $user->getId() ?></td>
                <td><?= $user->getName() ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<ul class="pagination">
    <?php for ($page = 1; $page <= $paginator->totalOfPages(); $page++) : ?>
        <li>
            <a href="<?= "/admins/users/page/{$page}" ?>"><?= $page ?></a>
        </li>
    <?php endfor; ?>
</ul>

<p><?= $paginator->entriesInfo() ?></p>