<div class="col-11 col-md-9" id="form-container">
    <div class="align-items-center">
        <h2>Todos os Usuários</h2>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($paginator->registers() as $user) : ?>
                    <tr>
                        <td><?= $user->getId() ?></td>
                        <td>
                            <p><?= $user->getName(); ?></p>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

        <ul class="pagination d-flex gap-2">
            <?php for ($page = 1; $page <= $paginator->totalOfPages(); $page++) : ?>
                <li>
                    <a class="btn btn-primary" href="<?= "/admins/users/page/{$page}" ?>"><?= $page ?></a>
                </li>
            <?php endfor; ?>
        </ul>

        <p><?= $paginator->entriesInfo() ?></p>
    </div>
</div>
