<div class="col-11 col-md-9" id="form-container">
    <div class="row gx-5">
        <h2>Vincular Colaborador ao Treinamento</h2>
        <form action="/trainingUser" method="POST" class="text-center mb-5">
            <div class="col-12 d-md-flex justify-content-between text-start">
                <div class="mb-3 col-5">
                    <label class="mb-2 form-label" for="user_id">Colaborador</label>
                    <select class="form-select" id="user_id" aria-label=" Nome do Colaborador" name="user[user_id]">
                        <option selected disabled value="">Selecione o Colaborador
                        </option>

                        <?php
                        foreach ($user as $user) { ?>
                            <option value="<?= $user->getId() ?>">
                                <?= $user->getname() ?></option>
                        <?php } ?>
                    </select>
                </div>

                <div class="mb-3 col-5">
                    <label class="mb-2 form-label" for="training_id">Treinamento</label>
                    <select class="form-select" id="training_id" aria-label="Nome do Treinamento" name="training[training_id]">
                        <option selected disabled value="">Selecione o Treinamento
                        </option>
                        <?php foreach ($training as $training) { ?>
                            <option value="<?= $training->getId() ?>">
                                <?= $training->getname() ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>
            <button type="submit" class="btn btn-primary w-25" id="btn-associate">Vincular</button>
        </form>
    </div>

    <div class="row gx-5">
        <h2>Colaboradores Vinculados</h2>
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th scope="col">Colaborador</th>
                    <th scope="col">Treinamento</th>
                    <th scope="col">Status</th>
                    <th scope="col">Excluir</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($trainingUser as $training_user) { ?>
                    <tr>
                        <td><?= $training_user->getUser()->getName() ?></td>
                        <td><?= $training_user->getTraining()->getName() ?></td>
                        <td><?= $training_user->getStatus() ?></td>
                        <td>
                            <form action="/trainingUser" method="POST">
                                <input type="hidden" name="_method" value="DELETE">
                                <input type="hidden" name="training_user[id]" value="<?= $training_user->getId() ?>">
                                <button type="submit" class="btn btn-danger"><i class="bi bi-trash"></i></button>
                            </form>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>
