<div class="col-11 col-md-9" id="form-container">
    <div class="align-items-center">
        <div class="d-flex justify-content-between">
            <h2>Meus treinamentos</h2>
        </div>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Treinamento</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
            <tbody>
                <?php foreach ($training as $trainingUser) : ?>
                    <tr>
                        <th><?= $trainingUser->getTraining()->getId() ?></th>
                        <td><?= $trainingUser->getTraining()->getName(); ?></td>
                        <td><?= $trainingUser->getStatus(); ?></td>
                        <td><a href="/trainingUser/<?= $trainingUser->getId() ?>/edit" class="btn btn-outline-primary mt-0">Editar</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
