<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Training System</title>
  <link rel="stylesheet" type="text/css" href="/assets/css/application.css">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>
  <?php if ($this->currentUser) : ?>
    Olá <?= $this->currentUser->getName(); ?>
    <a href="/logout">Sair</a> | <a href="/profile">Meu Perfil</a> | <a href="/trainings">Meus Treinamentos</a>
  <?php else : ?>
    <a href="/login">Entrar</a> | <a href="/sign-up">Registrar-se</a>
  <?php endif ?>

  <hr>

  <div class="container">
    <?php foreach (\App\Lib\Flash::message() as $type => $msg) : ?>
      <div class="alert alert-<?= $type ?>" role="alert">
        <?= $msg ?>
      </div>
    <? endforeach ?>

    <?php require $view ?>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </div>
</body>

</html>