<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Training System</title>
    <link rel="stylesheet" type="text/css" href="/assets/css/application.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
</head>

<body>
    <?php if ($this->currentUser) : ?>
        <header class="container-fluid py-3">
            <div class="container d-flex justify-content-between">
                <img class="col-5 col-md-2" src="/assets/images/logo.svg" alt="Logo">
                <div class="d-flex align-items-center gap-3">
                    <img class="avatar rounded-circle" src="<?= $this->currentUser()->avatar()->path() ?>" alt="avatar">
                    <div>
                        <p class="mb-0">Olá, <?= $this->currentUser->getName(); ?>!</p>
                        <a href="/profile">
                            <p class="mb-0">Opções da conta <i class="bi bi-chevron-right"></i>
                            </p>
                        </a>
                        <a id="logout" href="/logout">
                            <p class="mb-0">Sair</p>
                        </a>
                    </div>
                </div>
            </div>
        </header>

        <?php if ($this->currentUser->isAdmin()) : ?>
            <nav class="navbar navbar-expand-lg container-fluid mb-5">
                <div class="container">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="/trainings/new">Cadastrar Treinamento</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/trainings">Listar Treinamentos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/register">Cadastrar Colaborador</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/admins/users">Listar Colaboradores</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/associateTrainings">Vincular Colaborador</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        <?php endif ?>
    <?php endif ?>

    <main class="container">
        <?php foreach (\App\Lib\Flash::message() as $type => $msg) : ?>
            <div class="alert alert-<?= $type ?>" role="alert">
                <?= $msg ?>
            </div>
        <? endforeach ?>

        <?php require $view ?>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="assets/js/layouts.js"></script>
</body>

</html>
